language: java
jdk:
  - openjdk17

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r springboot-webservice ./*
  - mkdir -p deploy
  - mv springboot-webservice.zip deploy/springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-deploy-bucket
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travis-deploy-bucket
    key: springboot-webservice.zip
    bundle_type: zip
    application: ec2-loginjoindb-codedeploy-app  #CodeDeploy 애플리케이션 이름
    deployment_group: ec2-loginjoindb-codedeploy-app-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람5
notifications:
  email:
    recipients:
      - nissisoft21@gmail.com